CREATE TABLE "eco_city" (
  "id_city" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_name" varchar UNIQUE NOT NULL
);

CREATE TABLE "eco_category" (
  "id_category" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar UNIQUE NOT NULL
);

CREATE TABLE "eco_warehouses" (
  "id_warehouse" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_name" varchar UNIQUE NOT NULL
);

CREATE TABLE "eco_clients" (
  "id_client" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_name" varchar UNIQUE NOT NULL
);

CREATE TABLE "eco_products" (
  "id_product" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "products_name" varchar UNIQUE NOT NULL,
  "id_category" int NOT NULL,
  "unit_price" decimal NOT NULL
);

CREATE TABLE "eco_orders" (
  "id_order" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_code" varchar UNIQUE NOT NULL,
  "order_date" date NOT NULL,
  "id_clients" int NOT NULL,
  "id_city" int NOT NULL,
  "id_warehouse" int NOT NULL
);

CREATE TABLE "eco_order_detail" (
  "id_order_detail" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_order" int NOT NULL,
  "id_product" int NOT NULL,
  "quantity" int NOT NULL
);

CREATE TABLE "eco_inventory" (
  "id_inventory" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_product" int NOT NULL,
  "id_warehouse" int NOT NULL,
  "stock" int NOT NULL
);

CREATE UNIQUE INDEX ON "eco_order_detail" ("id_order", "id_product");

CREATE UNIQUE INDEX ON "eco_inventory" ("id_product", "id_warehouse");

ALTER TABLE "eco_products" ADD FOREIGN KEY ("id_category") REFERENCES "eco_category" ("id_category") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eco_orders" ADD FOREIGN KEY ("id_clients") REFERENCES "eco_clients" ("id_client") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eco_orders" ADD FOREIGN KEY ("id_city") REFERENCES "eco_city" ("id_city") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eco_orders" ADD FOREIGN KEY ("id_warehouse") REFERENCES "eco_warehouses" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eco_order_detail" ADD FOREIGN KEY ("id_order") REFERENCES "eco_orders" ("id_order") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "eco_order_detail" ADD FOREIGN KEY ("id_product") REFERENCES "eco_products" ("id_product") DEFERRABLE INITIALLY IMMEDIATE;
